/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.0-dev at Mon Mar 12 09:57:40 2018. */

#include "lsm6ds0_msg.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t lsm6ds0_msg_fields[11] = {
    PB_FIELD(  1, FLOAT   , REQUIRED, STATIC  , FIRST, lsm6ds0_msg, acc_x, acc_x, 0),
    PB_FIELD(  2, FLOAT   , REQUIRED, STATIC  , OTHER, lsm6ds0_msg, acc_y, acc_x, 0),
    PB_FIELD(  3, FLOAT   , REQUIRED, STATIC  , OTHER, lsm6ds0_msg, acc_z, acc_y, 0),
    PB_FIELD(  4, FLOAT   , REQUIRED, STATIC  , OTHER, lsm6ds0_msg, gyro_x, acc_z, 0),
    PB_FIELD(  5, FLOAT   , REQUIRED, STATIC  , OTHER, lsm6ds0_msg, gyro_y, gyro_x, 0),
    PB_FIELD(  6, FLOAT   , REQUIRED, STATIC  , OTHER, lsm6ds0_msg, gyro_z, gyro_y, 0),
    PB_FIELD(  7, FLOAT   , REQUIRED, STATIC  , OTHER, lsm6ds0_msg, q0, gyro_z, 0),
    PB_FIELD(  8, FLOAT   , REQUIRED, STATIC  , OTHER, lsm6ds0_msg, q1, q0, 0),
    PB_FIELD(  9, FLOAT   , REQUIRED, STATIC  , OTHER, lsm6ds0_msg, q2, q1, 0),
    PB_FIELD( 10, FLOAT   , REQUIRED, STATIC  , OTHER, lsm6ds0_msg, q3, q2, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
