# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lsm6ds0_msg.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='lsm6ds0_msg.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x11lsm6ds0_msg.proto\"\x9a\x01\n\x0blsm6ds0_msg\x12\r\n\x05\x61\x63\x63_x\x18\x01 \x02(\x02\x12\r\n\x05\x61\x63\x63_y\x18\x02 \x02(\x02\x12\r\n\x05\x61\x63\x63_z\x18\x03 \x02(\x02\x12\x0e\n\x06gyro_x\x18\x04 \x02(\x02\x12\x0e\n\x06gyro_y\x18\x05 \x02(\x02\x12\x0e\n\x06gyro_z\x18\x06 \x02(\x02\x12\n\n\x02q0\x18\x07 \x02(\x02\x12\n\n\x02q1\x18\x08 \x02(\x02\x12\n\n\x02q2\x18\t \x02(\x02\x12\n\n\x02q3\x18\n \x02(\x02')
)




_LSM6DS0_MSG = _descriptor.Descriptor(
  name='lsm6ds0_msg',
  full_name='lsm6ds0_msg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='acc_x', full_name='lsm6ds0_msg.acc_x', index=0,
      number=1, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='acc_y', full_name='lsm6ds0_msg.acc_y', index=1,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='acc_z', full_name='lsm6ds0_msg.acc_z', index=2,
      number=3, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='gyro_x', full_name='lsm6ds0_msg.gyro_x', index=3,
      number=4, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='gyro_y', full_name='lsm6ds0_msg.gyro_y', index=4,
      number=5, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='gyro_z', full_name='lsm6ds0_msg.gyro_z', index=5,
      number=6, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='q0', full_name='lsm6ds0_msg.q0', index=6,
      number=7, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='q1', full_name='lsm6ds0_msg.q1', index=7,
      number=8, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='q2', full_name='lsm6ds0_msg.q2', index=8,
      number=9, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='q3', full_name='lsm6ds0_msg.q3', index=9,
      number=10, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=176,
)

DESCRIPTOR.message_types_by_name['lsm6ds0_msg'] = _LSM6DS0_MSG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

lsm6ds0_msg = _reflection.GeneratedProtocolMessageType('lsm6ds0_msg', (_message.Message,), dict(
  DESCRIPTOR = _LSM6DS0_MSG,
  __module__ = 'lsm6ds0_msg_pb2'
  # @@protoc_insertion_point(class_scope:lsm6ds0_msg)
  ))
_sym_db.RegisterMessage(lsm6ds0_msg)


# @@protoc_insertion_point(module_scope)
