/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.0-dev at Mon Mar 12 09:57:40 2018. */

#ifndef PB_LSM6DS0_MSG_PB_H_INCLUDED
#define PB_LSM6DS0_MSG_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _lsm6ds0_msg {
    float acc_x;
    float acc_y;
    float acc_z;
    float gyro_x;
    float gyro_y;
    float gyro_z;
    float q0;
    float q1;
    float q2;
    float q3;
/* @@protoc_insertion_point(struct:lsm6ds0_msg) */
} lsm6ds0_msg;

/* Default values for struct fields */

/* Initializer values for message structs */
#define lsm6ds0_msg_init_default                 {0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define lsm6ds0_msg_init_zero                    {0, 0, 0, 0, 0, 0, 0, 0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define lsm6ds0_msg_acc_x_tag                    1
#define lsm6ds0_msg_acc_y_tag                    2
#define lsm6ds0_msg_acc_z_tag                    3
#define lsm6ds0_msg_gyro_x_tag                   4
#define lsm6ds0_msg_gyro_y_tag                   5
#define lsm6ds0_msg_gyro_z_tag                   6
#define lsm6ds0_msg_q0_tag                       7
#define lsm6ds0_msg_q1_tag                       8
#define lsm6ds0_msg_q2_tag                       9
#define lsm6ds0_msg_q3_tag                       10

/* Struct field encoding specification for nanopb */
extern const pb_field_t lsm6ds0_msg_fields[11];

/* Maximum encoded size of messages (where known) */
#define lsm6ds0_msg_size                         50

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define LSM6DS0_MSG_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
